### ISSUE TITLE
run simulation on KSP

### ISSUE THREAD

**Issue by abdxyz** [EmbersArc/SuccessiveConvexificationCpp#11]
hello,when I looked at your code,I find the code mainKsp.cpp used krpc to interact with KSP.
I'd like to simulation the code on KSP,too.
Can you give me a description of how to run KSP and how to setup the rocket and environment?

**Comment by EmbersArc** [comment]
It's still a work in progress and doesn't quite work yet. I use [krpc](https://github.com/krpc/krpc) to interact with KSP. But you can definitely start experimenting with it as well. Just install krpc and make the necessary changes to cmakelists.txt and the code. The program expects just a standard vessel with one engine at the bottom.

**Comment by abdxyz** [comment]
thanks a lot.I will have a try.
